#!/usr/bin/env bash
# Generate pages/docs/commands.md from the live ggvalet CLI help output.
# The reference is regenerated on every `make docs` so it never drifts from code.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/pages/docs/commands.md"

# Use a supplied binary, or build a temporary one for generation.
if [[ -n "${GGVALET_BIN:-}" && -x "$GGVALET_BIN" ]]; then
  BIN="$GGVALET_BIN"
else
  BIN="$ROOT/.bin/ggvalet-docs"
  mkdir -p "$ROOT/.bin"
  go build -o "$BIN" .
fi

help_cmd() {
  # --help short-circuits before PersistentPreRunE, so no config is required.
  NO_COLOR=1 "$BIN" "$@" --help 2>&1 || true
}

{
  cat <<'EOF'
# Command Reference

This page is generated automatically from `ggvalet --help` and the help text of
each top-level command. It is regenerated by `make docs` so it stays in sync
with the codebase.

## Top-level help

```text
EOF
  help_cmd
  cat <<'EOF'
```

## Commands

EOF

  # Extract top-level command names from the Available Commands block.
  cmds=()
  while IFS= read -r cmd; do
    [[ -z "$cmd" ]] && continue
    cmds+=("$cmd")
  done < <(help_cmd | awk '/^Available Commands:/{flag=1;next} /^Flags:/{flag=0} flag && /^  [a-z]/ {print $1}')

  for cmd in "${cmds[@]}"; do
    # help and completion are not useful as standalone reference sections.
    if [[ "$cmd" == "help" || "$cmd" == "completion" ]]; then
      continue
    fi
    echo "### $cmd"
    echo ""
    echo '```text'
    help_cmd "$cmd"
    echo '```'
    echo ""
  done
} > "$OUT"

echo "commands reference generated: $OUT"
